---
- name: Include tasks
  ansible.builtin.include_tasks: common/validation.yaml
  tags: always

- name: Run the platform specific tasks
  ansible.builtin.include_tasks: "restore.yaml"
  tags: always